# Generated by Django 5.2.7 on 2025-10-14 08:36

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(max_length=50)),
                ('timestamps', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Page name',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ref_type', models.CharField(max_length=20)),
                ('ref_type_id', models.IntegerField()),
                ('authors', models.CharField(max_length=255)),
                ('pub_year', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('journal', models.CharField(blank=True, max_length=255)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('issue', models.CharField(blank=True, null=True)),
                ('pages', models.CharField(blank=True, max_length=50)),
                ('abstract', models.TextField(blank=True)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('doi', models.URLField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('organisation', models.CharField(max_length=255)),
                ('project_title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Student name',
            },
        ),
    ]
