# Generated by Django 5.2.7 on 2025-10-14 11:37

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Students'},
        ),
        migrations.RenameField(
            model_name='page',
            old_name='name',
            new_name='template_name',
        ),
        migrations.RemoveField(
            model_name='page',
            name='activate_date',
        ),
        migrations.RemoveField(
            model_name='page',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='page',
            name='created',
        ),
        migrations.RemoveField(
            model_name='page',
            name='deactivate_date',
        ),
        migrations.RemoveField(
            model_name='page',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='page',
            name='timestamps',
        ),
        migrations.AddField(
            model_name='page',
            name='activation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='page',
            name='deactivation_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='landing_page',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=20),
        ),
    ]
