# Generated by Django 5.2.7 on 2025-10-15 10:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_page_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255)),
                ('team_type', models.CharField(blank=True, choices=[('Work Package', 'Work Package'), ('Technical', 'Technical'), ('Statistical Support', 'Statistical Support'), ('KEC', 'KEC')], max_length=20)),
                ('work_package', models.CharField(blank=True, choices=[('Farm and Design', 'Farm and Design'), ('Soils', 'Soils'), ('Biodiversity', 'Biodiversity'), ('Water', 'Water'), ('Gases', 'Gases'), ('Remote Sensing', 'Remote Sensing'), ('Data', 'Data'), ('Data Systems', 'Data Systems')], max_length=255)),
                ('skillset', models.TextField(blank=True, max_length=200)),
                ('image', models.URLField(blank=True)),
                ('staff_link', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Team Members',
            },
        ),
    ]
