# Generated by Django 5.2.7 on 2025-10-15 10:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='activate_date',
        ),
        migrations.RemoveField(
            model_name='team',
            name='deactivate_date',
        ),
        migrations.RemoveField(
            model_name='team',
            name='status',
        ),
        migrations.AddField(
            model_name='team',
            name='activation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='team',
            name='deactivation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
