# Generated by Django 5.2.7 on 2025-10-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_team_activate_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='deactivation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
