# Generated by Django 5.2.7 on 2025-10-15 15:04

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_page_deactivation_date_alter_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('Ror', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Organisations',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='course_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('goal', models.CharField(blank=True, max_length=200)),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=500)),
                ('additional_data', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('data', models.ManyToManyField(related_name='project', to='core.data')),
                ('student', models.ManyToManyField(related_name='project', to='core.student')),
                ('tags', models.ManyToManyField(related_name='project', to='core.tag')),
                ('themes', models.ManyToManyField(related_name='project', to='core.theme')),
            ],
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('full_description', ckeditor.fields.RichTextField(blank=True, max_length=500)),
                ('url', models.URLField(blank=True, null=True)),
                ('youtube_code', models.CharField(blank=True, max_length=100, null=True)),
                ('video_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('published', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonies', to='core.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonies', to='core.student')),
            ],
        ),
    ]
