# Generated by Django 5.2.7 on 2025-10-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_data_organisation_tag_theme_student_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='project',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='data',
            field=models.ManyToManyField(related_name='projects', to='core.data'),
        ),
        migrations.AlterField(
            model_name='project',
            name='student',
            field=models.ManyToManyField(related_name='projects', to='core.student'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(related_name='projects', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='themes',
            field=models.ManyToManyField(related_name='projects', to='core.theme'),
        ),
    ]
