# Generated by Django 5.2.7 on 2025-10-15 15:54

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_student_project_alter_project_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'Data Type'},
        ),
        migrations.AlterField(
            model_name='project',
            name='data',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='core.data'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='core.student'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='themes',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='core.theme'),
        ),
        migrations.AlterField(
            model_name='student',
            name='organisation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='project_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='full_description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonies', to='core.project'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonies', to='core.student'),
        ),
    ]
