# Generated by Django 5.2.7 on 2025-10-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_data_options_alter_project_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='student',
        ),
        migrations.AlterField(
            model_name='project',
            name='data',
            field=models.ManyToManyField(blank=True, related_name='project', to='core.data'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='project', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='project', to='core.theme'),
        ),
    ]
