# Generated by Django 5.2.7 on 2025-10-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_project_student_alter_project_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='data',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='project',
            name='themes',
        ),
        migrations.AddField(
            model_name='project',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='projects', to='core.student'),
        ),
    ]
