# Generated by Django 5.2.7 on 2025-10-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_project_data_remove_project_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='data',
            field=models.ManyToManyField(blank=True, related_name='projects', to='core.data'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='core.tag'),
        ),
        migrations.AddField(
            model_name='project',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='projects', to='core.theme'),
        ),
    ]
