# Generated by Django 5.2.7 on 2025-10-16 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_project_data_project_tags_project_themes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='core.project'),
        ),
    ]
