# Generated by Django 5.2.7 on 2025-10-16 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_student_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='students',
        ),
        migrations.AlterField(
            model_name='student',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.project'),
        ),
    ]
