# Generated by Django 5.2.7 on 2025-10-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_project_students_alter_student_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tags',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='themes',
            new_name='theme',
        ),
        migrations.AddField(
            model_name='project',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='projects', to='core.student'),
        ),
    ]
