# Generated by Django 5.2.7 on 2025-10-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_tags_project_tag_rename_themes_project_theme_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name_plural': 'Publications'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='testimony',
            options={'verbose_name_plural': 'Testimonies'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name_plural': 'Themes'},
        ),
    ]
