# Generated by Django 5.2.7 on 2025-10-16 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_project_options_alter_publication_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='student',
        ),
    ]
