# Generated by Django 5.2.7 on 2025-10-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_project_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimony',
            name='project',
        ),
    ]
