# Generated by Django 5.2.7 on 2025-10-16 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_testimony_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonies', to='core.project'),
        ),
    ]
