# Generated by Django 5.2.7 on 2025-10-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_testimony_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='on_top',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
    ]
